### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by aryan-mann**
Added instructions for running and explanation of its working.

### CODE REVIEW

**Comment by mukund26** [comment]
Thank you @aryan-mann

**Comment by mukund26** [comment]
@aryan-mann   you can make changes to programs to make it better

**Comment by aryan-mann** [comment]
I'll just change it so that it adds all space-separated numbers instead of the first two.

**Comment by mukund26** [comment]
yeah that would work.
happy coding and hacktoberfest

**Pull request merged**
